name = "temp-email-pages"
pages_build_output_dir = "../frontend/dist"
compatibility_date = "2024-05-13"

[[services]]
binding = "BACKEND"
service = "cloudflare_temp_email"
environment = "production"
[[d1_databases]]
binding = "DB"
database_name = "vmail"
database_id = "DÁN_DATABASE_ID_VỪA_COPY_VÀO_ĐÂY"
